name: customerapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  slide_to_act: ^2.0.0
  razorpay_flutter: ^1.2.7
  uuid: ^3.0.6
  fluttertoast: ^8.2.10
  lottie: ^2.2.0
  pin_code_fields: ^8.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/empty_cart.json
    
